const fs = require('fs');
let q = fs.readFileSync('C:/Projects/redos-hbx-extractor/lib/queryBuilder.ts', 'utf8');

// Find and replace the broken sql = \`...\` block with a clean string concatenation
const badStart = '    sql = \\`-- HBX (Snowflake) — FINANCE SUMMARY QUERY';
const badEnd = 'LIMIT 500\\`;';

const startIdx = q.indexOf(badStart);
const endIdx = q.indexOf(badEnd, startIdx) + badEnd.length;

if (startIdx === -1) {
  console.log('Pattern not found — checking current state...');
  const lines = q.split('\n');
  lines.slice(514, 545).forEach((l, i) => console.log(i + 515, ':', l.substring(0, 80)));
  process.exit(1);
}

const goodBlock = `    sql = [
      '-- HBX (Snowflake) — FINANCE SUMMARY QUERY — Generated by Red Health Data Hub',
      \`-- Intent: \${intent} | Date Logic: Finance (drop_date_ist via CTE)\`,
      \`-- Filters: \${appliedFilters.length} applied\`,
      '',
      'WITH base AS (',
      '    SELECT',
      '        fo.*,',
      '        COALESCE(',
      "            TO_DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata', fo.ASSIGNMENT_REACHEDDROPOFFAT_TIMESTAMP)),",
      '            TO_DATE(fo.FULFILLMENT_FULFILLED_AT_IST)',
      '        ) AS drop_date_ist',
      '    FROM Blade.core.red_blade_orders_final fo',
      '    WHERE',
      \`        \${baseWhere}\`,
      ')',
      'SELECT',
      selectPart.replace(/fo\\./g, ''),
      'FROM base',
      \`WHERE drop_date_ist BETWEEN '\${from}' AND '\${toDate}'\`,
      \`GROUP BY \${dims.map(d => d.replace(/fo\\./g, '')).join(', ')}\`,
      \`ORDER BY \${dims[0].replace(/fo\\./g, '')} ASC\`,
      'LIMIT 500',
    ].join('\\n');`;

q = q.slice(0, startIdx) + goodBlock + q.slice(endIdx);
fs.writeFileSync('C:/Projects/redos-hbx-extractor/lib/queryBuilder.ts', q, 'utf8');
console.log('Fixed! CTE block replaced cleanly.');